### ISSUE TITLE
Error while closing connection

### ISSUE THREAD

**Issue by redixin** [ronf/asyncssh#15]
When running slightly modified sample (https://github.com/ronf/asyncssh/blob/master/examples/simple_client.py)

(I've just changed credentials in create_connection)

    import asyncio, asyncssh, sys
    class MySSHClientSession(asyncssh.SSHClientSession):
        def data_received(self, data, datatype):
            print(data, end='')
        def connection_lost(self, exc):
            if exc:
                print('SSH session error: ' + str(exc), file=sys.stderr)
    class MySSHClient(asyncssh.SSHClient):
        def connection_made(self, conn):
            print('Connection made to %s.' % conn.get_extra_info('peername')[0])
        def auth_completed(self):
            print('Authentication successful.')
    @asyncio.coroutine
    def run_client():
        conn, client = yield from asyncssh.create_connection(MySSHClient, 'localhost', username='root', password='123', port=1234, client_keys=[])
        with conn:
            chan, session = yield from conn.create_session(MySSHClientSession, 'env')
            yield from chan.wait_closed()
    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SSH connection failed: ' + str(exc))

This error occured:

    Connection made to 127.0.0.1.
    Authentication successful.
    SHELL=/bin/bash
    SSH_CLIENT=172.17.42.1 49465 1234
    USER=root
    MAIL=/var/mail/root
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    PWD=/root
    SHLVL=1
    HOME=/root
    LOGNAME=root
    SSH_CONNECTION=172.17.42.1 49465 172.17.0.5 1234
    _=/usr/bin/env
    Traceback (most recent call last):
      File "../assh.py", line 28, in <module>
        asyncio.get_event_loop().run_until_complete(run_client())
      File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
        return future.result()
      File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
        raise self._exception
      File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
        result = next(coro)
      File "../assh.py", line 25, in run_client
        yield from chan.wait_closed()
      File "/home/eye/code/rally-ci/.tox/py34/lib/python3.4/site-packages/asyncssh/connection.py", line 179, in __exit__
        if not self._loop.is_closed():
    AttributeError: '_UnixSelectorEventLoop' object has no attribute 'is_closed'

pip freeze:

PyYAML==3.11
argparse==1.3.0
asyncssh==1.1.1
extras==0.0.3
fixtures==1.2.0
flake8==2.4.1
linecache2==1.0.0
mccabe==0.3
mock==1.0.1
pbr==1.0.1
pep8==1.5.7
pycrypto==2.6.1
pyflakes==0.8.1
python-mimeparse==0.1.4
python-subunit==1.1.0
-e git+ci49:~/rally-ci@296a4554e4f946b162f2d7a662f24b2d26640e55#egg=rallyci-master
six==1.9.0
testrepository==0.0.20
testtools==1.8.0
traceback2==1.4.0
unittest2==1.0.1
websockets==2.4

python --version
Python 3.4.0

**Comment by ronf** [comment]
Yeah - I just discovered this today myself, when I tried running the code on Ubuntu 14.04. Apparently the is_closed() method that I'm depending on here was only added in Python 3.4.2, and so the wait_closed() method I added doesn't work in Python 3.4.0 or 3.4.1. It works fine in 3.4.2 and later.

A simple way to work around this for now is to not use the "with" syntax. Instead, replace run_client() with:

```python
def run_client():
    conn, client = yield from asyncssh.create_connection(MySSHClient, 'localhost', username='root', password='123', port=1234, client_keys=[])
    chan, session = yield from conn.create_session(MySSHClientSession, 'env')
    yield from chan.wait_closed()
    chan.close()
```

I'm still debating about the right way to fix this, as I ran into problems calling close() unconditionally like this from the exit handler under certain types of program terminations. If I remember right, it would fail when trying to Ctrl-C out of the program without a guard here, for instance.

**Comment by ronf** [comment]
I've updated SSHConnection to no longer depend on the Python 3.4.2 is_closed() call on the event loop. Unfortunately, this means I need to avoid the race condition by trying to catch and parse the RuntimeError which is thrown, which isn't very pretty.

This fix is now in the "develop" branch and should avoid the problem reported here on Python versions older than 3.4.2. I'll roll the fix into "master" and make a new release available with it soon.

**Comment by ronf** [comment]
The fix for this should now be available in version 1.2.0 on PyPI.
