### ISSUE TITLE
Breakage seen in py3.4 asyncssh 1.15.1

### ISSUE THREAD

**Issue by mdear** [ronf/asyncssh#187]
The following error was seen when upgrading from 1.14.0 to 1.15.1:

`TypeError: create_server() got an unexpected keyword argument 'reuse_port'`

On pypi you claim python 3.4 compatibility, but the `create_server `api does not have the `reuse_port `argument in python34 : [https://docs.python.org/3.4/library/asyncio-eventloop.html#asyncio.BaseEventLoop.create_server](url)

**Comment by ronf** [comment]
Thank you for the report!

I do run tests on every build here against all releases from 3.4 to 3.7, but not every version of of each of those. Looking more closely, it appears that the reuse_port argument was only added in the 3.4.4 release, though the documentation doesn't actually state that.

Here's something I think should fix it:

```patch
--- a/asyncssh/connection.py
+++ b/asyncssh/connection.py
@@ -90,7 +90,7 @@ from .mac import get_mac_algs
 
 from .misc import ChannelOpenError, DisconnectError, PasswordChangeRequired
 from .misc import async_context_manager, create_task, get_symbol_names
-from .misc import ip_address, map_handler_name
+from .misc import ip_address, map_handler_name, python344
 
 from .packet import Boolean, Byte, NameList, String, UInt32
 from .packet import PacketDecodeError, SSHPacket, SSHPacketHandler
@@ -5170,7 +5170,7 @@ def create_server(server_factory, host=None, port=_DEFAULT_PORT, *,
            port other existing sockets are bound to, so long as they all
            set this flag when being created. If not specified, the
            default is to not allow this. This option is not supported
-           on Windows.
+           on Windows or Python versions prior to 3.4.4.
        :param server_host_keys: (optional)
            A list of private keys and optional certificates which can be
            used by the server as a host key. Either this argument or
@@ -5420,13 +5420,15 @@ def create_server(server_factory, host=None, port=_DEFAULT_PORT, *,
     if x509_trusted_certs is not None:
         x509_trusted_certs = load_certificates(x509_trusted_certs)
 
+    reuse_port_arg = dict(reuse_port=reuse_port) if python344 else {}
+
     logger.info('Creating SSH server on %s', (host, port))
 
     return (yield from loop.create_server(conn_factory, host, port,
                                           family=family, flags=flags,
                                           backlog=backlog,
                                           reuse_address=reuse_address,
-                                          reuse_port=reuse_port))
+                                          **reuse_port_arg))
 
 
 @async_context_manager
```

I actually already had a variable I could leverage for the version check, as I previously needed to check against Python 3.4.4 or later due to the change from asyncio.async to asyncio.ensure_future.

After a bit of testing, I'll get this checked into the "develop" branch, and include it in the next release so that others don't run into this.

**Comment by ronf** [comment]
This is now available in the "develop" branch as commit e8d8c24.

**Comment by ronf** [comment]
This fix is now available in 1.16.0.
